Hackathon/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls')),
    path('',include('product.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.index,name='home'),

    path('register/', views.registration_view, name='register'),

    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html')
         , name='password_reset_confirm'),
    path('password-reset-complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
         name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html'),
         name='password_change'),

 ]

product/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.conf import settings
# Create your models here.
from django.urls import reverse
from mptt.models import MPTTModel,TreeForeignKey

from django.utils import timezone
import random
user=settings.AUTH_USER_MODEL



class GroupAddress(models.Model):

    street=models.CharField(max_length=200,blank=True,null=True,default="StreetA")
    locality=models.CharField(max_length=200,blank=True,null=True,default="Locality A")
    #TODO add validators here
    Pincode=models.IntegerField(blank=True,null=True,default=401503)
    Post=models.CharField(blank=True,null=True,max_length=150,default="POST-A")
    District=models.CharField(max_length=200,blank=True,null=True,default="MUMBAI")
    State=models.CharField(max_length=200,blank=True,null=True,default="MAHARASHTRA")



class Group(models.Model):

    name=models.CharField(max_length=50)
    admins= models.ManyToManyField(user, blank=True,related_name="group_admins")
    group_address=models.OneToOneField(GroupAddress,on_delete=models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return str(self.name)


class RequestForJoinGroup(models.Model):

    user=models.OneToOneField(user,on_delete=models.CASCADE)
    group=models.ForeignKey(Group,on_delete=models.CASCADE)
    is_accepted = models.BooleanField(default=False)
    is_cancelled= models.BooleanField(default=False)




#
#
# class GroupAdmin(models.Model):
#     group=models.OneToOneField(Group,on_delete=models.CASCADE)
#     group_admins=models.ManyToManyField(user,blank=True)
#
#     def __str__(self):
#         return str(self.group.name)






class Category(models.Model):

    name=models.CharField(default="Hammers",max_length=100)

    def __str__(self):
        return str(self.name)


class Product(models.Model):

    user=models.ForeignKey(user,on_delete=models.CASCADE)
    name=models.CharField(default="Hammer",max_length=20)
    desc=models.TextField(default="This is the hammer")
    category=models.ForeignKey(Category,on_delete=models.SET_NULL,blank=True,null=True)
    is_borrowed=models.BooleanField(default=False)
    is_on_rent=models.BooleanField(default=False)
    thumbnail=models.ImageField(upload_to='product_images',blank=True,null=True)
    group=models.ForeignKey(Group,on_delete=models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return str(self.name)+" "+str(self.user.username)

    def get_product_absolute_url(self):
        return reverse('product-detail',kwargs={'id':self.id})


TIMES=(

    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (7,7),
    (15,15),
)

product_list=['hammer','hpenvy-234 charger','screw driver','drilling machine','machine','mechanical drive']
x=product_list[random.randint(0,len(product_list)-1)]
class RequestForProduct(models.Model):

    user = models.ForeignKey(user, on_delete=models.CASCADE)
    product_name = models.CharField(default=x, max_length=50)
    product_desc = models.TextField(default=f"This is the {x}",blank=True,null=True)
    request_in_brief=models.TextField(default=f"I need a {x} for something",blank=True,null=True,)
    product_category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    is_urgent= models.BooleanField(default=False)
    date_needed_by=models.DateTimeField(default=timezone.now(),blank=True,null=True,help_text="Format 2021-04-11 04:08:08")
    time_needed_by=models.IntegerField(choices=TIMES,blank=True,null=True)
    return_date=models.DateTimeField(default=timezone.now(),blank=True,null=True,help_text="Format 2021-04-11 04:08:08")
    is_submitted=models.BooleanField(default=False)
    group=models.ForeignKey(Group,on_delete=models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return str(self.user)+str(self.product_name)

    def get_request_absolute_url(self):
        return reverse('request-detail',kwargs={'id':self.id})


class RespondToRequest(models.Model):
    user=models.ForeignKey(user,on_delete=models.CASCADE)
    request_for_product = models.OneToOneField(RequestForProduct, on_delete=models.CASCADE)
    message=models.CharField(max_length=200,default="I have this one")


    def __str__(self):
        return f"{self.user.username} {self.request_for_product.product_name}"


class CommentTORequest(MPTTModel):
    request_for_product=models.ForeignKey(RequestForProduct,on_delete=models.CASCADE)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    content = models.TextField(default="This is the comment")
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)


    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return f'comment on {self.request_for_product.product_name}'

templates/main/a_footer.html
<!-- footer -->
{% load static %}
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6 col-12">
				<div class="footer-logo">
					<img style="" src="{% static 'main/img/logo.png' %}"/>
{#					<img style="max-width: 100px; height: 100px" src="https://raw.githubusercontent.com/internyuva/internyuva/master/static/main/img/InternYuvaResized.png"/>#}

				</div>
				<div class="about-data">
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-12 mt-4 mt-md-0">
				<h3 class="footer-links">
					Useful Links
				</h3>
				<div class="row quick-links">
					<div class="col-12 mb-4">
						<a href="#"><i class="fal fa-chevron-double-right mr-2"></i>Home</a>
					</div>
					<div class="col-12 mb-4">
						<a href="#"><i class="fal fa-chevron-double-right mr-2"></i>Product</a>
					</div>
					<div class="col-12 mb-4">
						<a href="#"><i class="fal fa-chevron-double-right mr-2"></i>About Us</a>
					</div>
					<div class="col-12 mb-4">
						<a href="#"><i class="fal fa-chevron-double-right mr-2"></i>Contact Us</a>
					</div>
				</div>
			</div>
			<div class="col-lg-3 mt-4 mt-md-5 mt-lg-0">
				<h3 class="footer-links">
					Contact
				</h3>
				<div class="contact-info">
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. aliqua. Ut.</p>
	                <ul>
	                  <li class="pt-0">
	                    <a href="mailto:info@learning.com"><span><i class="far fa-envelope mr-3"></i> info@learning.com</span></a>
	                  </li>
	                  <li>
	                    <a href="tel:+12 3456 7890"><span><i class="fal fa-phone-alt mr-3"></i> +12 3456 7890</span></a>
	                  </li>
					</ul>
	            </div>
	        </div>
            {% comment %}
	        <div class="col-lg-3 mt-4 mt-md-5 mt-lg-0">
				<h3 class="footer-links">
					Follow Us
				</h3>
				<div class="social-links">
	                <ul class="d-flex">
	                  <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
	                  <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
	                  <li><a href="#" target="_blank"><i class="fab fa-skype"></i></a></li>
	                  <li><a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
	                </ul>
	            </div>
			</div>
			{% endcomment %}
		</div>
	</div>
</footer>

<!-- signup Modal -->

<script src="{% static 'main/js/custom.js' %}"></script>

templates/main/a_header.html
{%  load static %}
<head>
  <title>Index</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- bootstarp -->
  <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
  <script src="{% static 'main/js/jquery.min.js' %}"></script>
  <script src="{% static 'main/js/popper.min.js' %}"></script>
  <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'main/js/wow.min.js' %}"></script>
  <!-- owl carousel -->
  <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
  <script src="{% static 'main/js/owl.carousel.js' %}"></script>
  <!-- custom js -->
  <!-- custom css -->
  <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/responsive.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
  <!-- fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="styleshefoet">
  <script src="{% static 'main/js/font-awesome-5-pro.js' %}"></script>
</head>

templates/main/a_navbar.html
{% load static %}

<!-- mobile menu -->
    <div class="mobile-menu d-block d-lg-none">
        <div id="mySidenav" class="sidenav">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="#">HOME</a>
          <a href="#">REQUESTS</a>
          <a href="#">PRODUCTS</a>
          <a href="#">PRODUCTS ON RENT</a>
            {% if request.user.is_authenticated %}
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">PROFILE</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">YOUR PRODUCT LIST</a>
                    <a class="dropdown-item" href="#">BORROWED PRODUCTS</a>
                    <a class="dropdown-item" style="color: red" href="{% url 'logout' %}">LOGOUT</a>
                  </div>
            {% else %}
                <a href="{% url 'login' %}">SIGN IN</a>
            {% endif %}
        </div>
    </div>

<!-- header -->
<header>
		<div class="container">
			<div class="row mt-0 mt-lg-2">
				<div class="col-lg-12">
					<nav class="navbar navbar-expand-lg p-0">
					  <a class="navbar-brand m-0 p-0" href="#">
					  	<img style="max-width: 100px; height: 100px" src="{% static 'main/img/la.jpg' %}"/>
{#					  	<img style="max-width: 100px; height: 100px" src="https://raw.githubusercontent.com/internyuva/internyuva/master/static/main/img/InternYuvaResized.png"/>#}
					  </a>
					  <div class="mobile-menu-open d-block d-lg-none" onclick="openNav()">
							<i><img src="{% static 'main/img/menu-icon.png' %}"></i>
                      </div>
					  <div class="collapse navbar-collapse pr-2" id="collapsibleNavbar">
				      <ul class="navbar-nav ml-auto align-items-center">
					      <li class="nav-item">
					        <a class="nav-link" href="{% url 'index-page' %}">HOME</a>
					      </li>
					      <li class="nav-item">
					        <a class="nav-link" href="{% url 'request-page' %}">REQUESTS</a>
					      </li>
                            <li class="nav-item">
					        <a class="nav-link" href="{% url 'product-page' %}">PRODUCTS</a>
					      </li>
{#                          <li class="nav-item">#}
{#					        <a class="nav-link" href="#">PRODUCTS ON RENT</a>#}
{#					      </li>#}



										     &nbsp;&nbsp;&nbsp;&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;

                                {% if request.user.is_authenticated %}
{#                                    <a href="#" data-toggle="modal">Profile</a>#}
                                    <div class="dropdown">
                                         <li class="nav-item">
                                            <a class="nav-link" href="#">PROFILE</a>
                                         </li>
                                          <div class="dropdown-content">
                                            <a href="#">{{ request.user.email }}</a>
                                            <a href="{% url 'view_send_joining_request' %}">JOINING REQUEST</a>
                                            <a href="{% url 'request-page-user' %}">YOUR REQUEST</a>
                                            <a href="#">BORROWED History</a>
                                            <a style="color: red" href="{% url 'logout' %}"><span>LOGOUT</span></a>
                                          </div>
                                    </div>
                                    {% if not request.user.group %}
                                        <a class="nav-link theme-btn" href="{% url 'groups' %}"><span>Join Group</span></a>
                                        <a class="nav-link theme-btn" href="{% url 'create-group' %}"><span>Create Group</span></a>
                                    {% else %}
                                        <a class="nav-link theme-btn" href="{% url 'request_list_for_joining_group' %}"><span>Your Group</span></a>
                                    {% endif %}
                                {% else %}
                                    <a class="nav-link theme-btn" href="{% url 'register' %}"><span>SIGN IN</span></a>
                                {% endif %}

{#					      </li>#}
					    </ul>
					  </div>
				    </nav>
				</div>
			</div>
	</div>
</header>

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    {% include 'main/a_header.html' %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
</head>
<body>
{% include 'main/a_navbar.html' %}

        {% if messages %}
            <div class="mt-0 pt-4">
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% endfor %}
            </div>
      {% endif %}
    {% block content %}

    {% endblock %}
{#{% include 'main/a_footer.html' %}#}

</body>

</html>

templates/main/group_admin.html
{% extends 'main/base.html' %}

{% block style %}
  <style>
  	@media only screen and (max-width: 554px){
  	.vid-wid{
  		width: 250px;
  	}
  }
  </style>
{% endblock %}

{% block content %}

{#    <section class="page-title">#}
        <div class="container" style="color: black">
            <div class="row">
                <div class="col-lg-12 pt-0 pt-lg-5">
                    <div class="text-center pt-0 pt-lg-5">
                        <h2 class="text-black-50"> Group Name :- {{ group.name }}</h2>
                        <h2 class="text-black-50"> Group Address </h2>
                           <h3 class="text-black-50"> {{ group.group_address.street }},
                                                        {{ group.group_address.locality }},
                                                        {{ group.group_address.Pincode }},
                                                        {{ group.group_address.Post }},
                                                        {{ group.group_address.District }},
                                                        {{ group.group_address.State }}</h3>
                        <br>
                        <br>
                    </div>
                </div>
            </div>
                {% if message %}
                    <h3>Sorry You are not admin</h3>
                {% else %}
                    {% for obj in requests %}
                        <div class="row">
                            <h3>{{ obj.user }}</h3>
                            <a href="{% url 'accept_request_for_joining_group' obj.user.username %}" class="btn btn-outline-info">Accept</a>
                            <a href="{% url 'cancel_group_joining_request_by_admin' obj.user.username %}" class="btn btn-outline-info">Cancel</a>
                        </div>
                    {% empty %}
                        <h3>You Don't Have Any Request</h3>
                    {% endfor %}
                {% endif %}
        <br>
        <br>
                <h3>Members</h3>
                {% for obj in users %}
                    <div class="row">
                            <h3 style="color: black">{{ forloop.counter }} ] {{ obj.email }}</h3>
{#                            <a href="{% url 'accept_request_for_joining_group' obj.user.username %}" class="btn btn-outline-info">Accept</a>#}
{#                            <a href="{% url 'cancel_group_joining_request_by_admin' obj.user.username %}" class="btn btn-outline-info">Cancel</a>#}
                    </div>
                {% empty %}
                    <h3 style="color: black">No Members</h3>
                {% endfor %}

        </div>
{#    </section>#}



{% endblock %}

templates/main/group_request.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
  <style>
  	@media only screen and (max-width: 554px){
  	.vid-wid{
  		width: 250px;
  	}
  }
  </style>
{% endblock %}

{% block content %}

{#    <section class="page-title">#}
        <div class="container">
                <div class="col-lg-12 pt-0 pt-lg-5">
                    <div class="text-center">
                        <div class="col-lg-6">
                    <br>
                        <br>
                        <br>
                        <div class="contact-box text-center">
                                <div class="contact-icon mb-4">
    {#                                <div class="course-img">#}
    {#									<img src="{{ obj.thumbnail.url }}">#}
    {#								</div>#}
                                    <br>
                                    <br>
                                    <h5>{{ group.name }}</h5>
                                    <h6>{{ group.group_address }}</h6>

                                </div>
                                <div class="course-btn">
                                    <a href="#" class="">
                                        <i class="fas fa-play-circle mr-2" aria-hidden="true"></i>
                                        <span>Requested</span>
                                    </a>
                                    <a href="{% url 'cancel_group_joining_request' %}" class="theme-btn">
                                        <i class="fas fa-play-circle mr-2" aria-hidden="true"></i>
                                        <span>Cancel</span>
                                    </a>
                                </div>
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    </div>
                </div>
            </div>

{#    </section>#}

{% endblock %}

templates/main/groups.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
  <style>
  	@media only screen and (max-width: 554px){
  	.vid-wid{
  		width: 250px;
  	}
  }
  </style>
{% endblock %}

{% block content %}

{#    <section class="page-title">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-lg-12 pt-0 pt-lg-5">#}
{#                    <div class="text-center pt-0 pt-lg-5">#}
{#                        <h2 class="text-white">Requests</h2>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}

<!-- banner -->


    <section class="contact-data">
        <div class="container">
        <form>
            <div class="form-row">
                <div class="form-group col-8">
                    <div class="input-group">
                        <input class="form-control py-2 border-right-0 border" type="search" name="group_name" placeholder="Search Group Here" />
                        <span class="input-group-append">
                            <div class="input-group-text bg-transparent">
                                <i class="fa fa-search"></i>
                            </div>
                        </span>
                    </div>
                </div>
                <button type="submit" class="btn btn-outline-info">Search</button>
            </div>
        </form>
            <div id="contact-bg" class="row mt-5">
                {% for obj in objects %}
                    <div class="col-lg-6">
                    <br>
                        <br>
                        <br>
                        <div class="contact-box text-center mb-5 mb-lg-0">
                            <div class="contact-icon mb-4">
{#                                <div class="course-img">#}
{#									<img src="{{ obj.thumbnail.url }}">#}
{#								</div>#}
                                <br>
                                <br>
                                <h5>{{ obj.name }}</h5>
                                <h6>{{ obj.group_address }}</h6>
                            </div>
                            <div class="course-btn">
                                <a href="{% url 'send_joining_request' obj.id %}" class="theme-btn">
                                    <i class="fas fa-play-circle mr-2" aria-hidden="true"></i>
                                    <span>request to join</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>
                {% endfor %}
            </div>
        </div>
</section>
{% endblock %}

templates/main/request_detail.html
{% extends 'main/base.html' %}

{% load static %}
{% load mptt_tags %}
{% load crispy_forms_tags %}
{% block style %}
  <style>
  	@media only screen and (max-width: 554px){
  	.vid-wid{
  		width: 250px;
  	}
  }
  </style>
{% endblock %}

{% block content %}

{#    <section class="page-title">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-lg-12 pt-0 pt-lg-5">#}
{#                    <div class="text-center pt-0 pt-lg-5">#}
{#                        <h2 class="text-white">Requests</h2>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
    <div style="color: black" class="text-center pt-0 pt-lg-5">
        <h2>{{ object.product_name }}</h2>
        <h4>{{ object.product_desc }}</h4>
        <h5>{{ object.request_in_brief }}</h5>
        <form>
            <div class="form col-4">
                <div class="form-group center">
                    <div class="input-group">
                        <input class="form-control py-2 border-right-0 border" style="border: black" type="search" name="respond_input" placeholder="I have this one" />
                        <span class="input-group-append">
                            <div classss="input-group-text bg-transparent">
                                <i class="fa fa-search"></i>
                            </div>
                        </span>
                    </div>
                </div>
                <button type="submit" class="btn btn-outline-info">RESPOND</button>
            </div>
            <br>
            <br>
        </form>


    </div>

            <div class="container">
                <div class="post-comments" style="color: black">
                      <header>
                        <h3 class="h6">Post Comments<span class="no-of-comments">( {{ comments.count }} )</span></h3>
                      </header>
                      {% recursetree comments %}
                      <div class="comment">
                        <div class="comment-header d-flex justify-content-between">
                          <div class="user d-flex align-items-center">
                            <div class="image"><img src="{% static 'img/user.svg' %}" alt="..." class="img-fluid rounded-circle"></div>
                            <div class="title"><strong>{{ node.name }}</strong><span class="date">May 2016 level[{{ node.level }}]</span></div>
                          </div>
                        </div>
                        <div class="comment-body">
                          <p id="{{ node.id }}">{{ node.content }}</p>
                        </div>
                          {% if node.level < 6 %}
                             <a class="btn btn-outline-info" onclick="myFunction({{ node.id }})">Reply</a>
                          {% endif %}
                      </div>
                        {% if not node.is_leaf_node %}
                          <div class="children pl-2 pl-md-5">
                            {{ children }}
                          </div>
                        {% endif %}
                  {% endrecursetree %}
                  {% comment %}
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image"><img src="img/user.svg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="title"><strong>Nikolas</strong><span class="date">May 2016</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                    </div>
                  </div>
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image"><img src="img/user.svg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="title"><strong>John Doe</strong><span class="date">May 2016</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                    </div>
                  </div>
                  {% endcomment %}
                </div>
                <div class="add-comment" style="color: black">
                  <header>
                    <h3 class="h6">Leave a reply</h3>
                  </header>
                  <form method="POST">
                      {% csrf_token %}
                      <fieldset class="form-group">
                          <legend class="'border-bottom mb-4">Comment  Form </legend>
                         {{ comment_form | crispy  }}
                      </fieldset>
                      <div class="form-group">
                          <button class="btn btn-outline-info" type="submit">Send</button>
                      </div>
                  </form>
                  {% comment %}
                  <form action="#" class="commenting-form">
                    <div class="row">
                      <div class="form-group col-md-6">
                        <input type="text" name="username" id="username" placeholder="Name" class="form-control">
                      </div>
                      <div class="form-group col-md-6">
                        <input type="email" name="username" id="useremail" placeholder="Email Address (will not be published)" class="form-control">
                      </div>
                      <div class="form-group col-md-12">
                        <textarea name="usercomment" id="usercomment" placeholder="Type your comment" class="form-control"></textarea>
                      </div>
                      <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-secondary">Submit Comment</button>
                      </div>
                    </div>
                  </form>
                  {% endcomment %}
                </div>
            </div>

    <script>
        function formExit() {
            document.getElementById("newForm").remove();
        }
        function myFunction(id) {
           if (document.contains(document.getElementById("newForm"))) {
             document.getElementById("newForm").remove();
           }
             var d1 = document.getElementById(id);
             d1.insertAdjacentHTML('afterend',
                  '<form id="newForm" class="form-insert" method="post"> \
                        <div class="d-flex justify-content-between">\
                        <h2>Reply:</h2>\
                        <div><button type="button" class="btn btn-danger" onclick="formExit()"">Close</button></div></div> \
                        \
                        <option value="' + id + '" selected="' + id + '"></option> \
                        </select> \
                        <label for="id_content">Content:</label> \
                        <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                        {% csrf_token %} \
                        <button type="submit" class="btn btn-outline-info">Submit</button> \
                  </form>');

            //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
        }
      $('#myForm').trigger("reset");
      </script>

{% endblock %}